stages:
  - build
  - package
  - deploy

.ppc-build-base:
  timeout: 6h

  only:
    - tags
    - web

  tags:
    - ppc64le

build:
  extends: .ppc-build-base
  stage: build

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - dnf install -y findutils
    - make gitlab-build
    # TODO: Once https://gitlab.com/gitlab-org/gitlab/issues/22638 is fixed,
    # just pass the variable
    - echo "export ARTIFACTS_URL=${CI_JOB_URL}/artifacts/raw/target" > artifacts_url.sh

  artifacts:
    paths:
      - target/*.tar*
      - target/*.rpm
      - artifacts_url.sh

  cache:
    key: chromium-build-cache
    paths:
      - .ccache

create-repo:
  extends: .ppc-build-base
  stage: package
  dependencies:
    - build

  script:
    - dnf install -y findutils createrepo_c
    - mkdir -p repo/{chromium,chromium-testing}
    - . artifacts_url.sh
    - createrepo -v -u ${ARTIFACTS_URL} -o repo/chromium target
    - createrepo -v -u ${ARTIFACTS_URL} -o repo/chromium-testing target

  artifacts:
    paths:
      - repo/

.repo-deploy-base: &repo-deploy-base
  stage: deploy

  only:
    - tags
    - web

  trigger:
    strategy: depend

repo-deploy:
  <<: *repo-deploy-base
  trigger:
    project: chromium-ppc64le/dnf/chromium

testing-repo-deploy:
  <<: *repo-deploy-base
  trigger:
    project: chromium-ppc64le/dnf/chromium-testing

