stages:
  - build
  - deploy

build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  only:
    - tags
    - web

  tags:
    - ppc64le

  stage: build

  timeout: 6h

  script:
    - dnf install -y findutils createrepo_c gawk
    - make gitlab-build

  artifacts:
    paths:
      - target/*.tar*
      - target/*.rpm

pages:
  stage: deploy
  dependencies:
    - build

  only:
    - tags
    - web

  when: manual

  tags:
    - ppc64le

  script:
    - mkdir -p public/dnf-repo
    - createrepo --retain-old-md 10 -v -u ${CI_JOB_URL}/artifacts/raw/target -o public/dnf-repo target
    - ./filelist2html.sh public > public/index.html
    - ./filelist2html.sh public/dnf-repo > public/dnf-repo/index.html
    - ./filelist2html.sh public/dnf-repo/repodata > public/dnf-repo/repodata/index.html

  artifacts:
    paths:
      - public

