# Copyright 2019 Colin Samples
#
# SPDX-License-Identifier: Apache-2.0
#

stages:
  - prepare
  - build
  - package
  - deploy

variables:
  BUILD_CONTAINER: $CI_REGISTRY_IMAGE/chromium-build-image:$CI_COMMIT_REF_NAME
  GIT_SUBMODULE_STRATEGY: recursive

.ppc-build-base:
  image: $BUILD_CONTAINER
  timeout: 16h

  only:
    - tags
    - web

  tags:
    - ppc64le
    - docker

#
# Prepare
#

build-container:
  extends: .ppc-build-base
  image: fedora:latest
  stage: prepare

  variables:
    _BUILDAH_STARTED_IN_USERNS: ""
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
    GIT_SUBMODULE_STRATEGY: none

  script:
    - dnf install
        --setopt=install_weak_deps=False
        --disablerepo="*modular*"
        -y buildah
    - sed -e 's/^driver =.*/driver = "vfs"/'
          -e '/^mountopt =.*/d'
          -i /etc/containers/storage.conf
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - buildah bud -t $BUILD_CONTAINER .
    - buildah push $BUILD_CONTAINER

#
# Build
#
chromium:
  extends: .ppc-build-base
  stage: build

  script:
    - make -C docker-root -j16
    # TODO: Once https://gitlab.com/gitlab-org/gitlab/issues/22638 is fixed,
    # just pass the variable
    - echo "export ARTIFACTS_URL=$CI_JOB_URL/artifacts/raw/target" > artifacts_url.sh

  artifacts:
    paths:
      - docker-root/target/*.tar*
      - docker-root/target/*.rpm
      - docker-root/ccache*xz
      - artifacts_url.sh

  cache:
    key: chromium-build-cache
    paths:
      - docker-root/.ccache
      - docker-root/chromium-*.tar.xz
      - docker-root/llvm-*.tar.zstd

ungoogled-chromium:
  extends: chromium

  variables:
    UNGOOGLED: 1

#
# Package
#
.create-repo-base:
  image: fedora:latest
  stage: package

  only:
    - tags
    - web

  variables:
    GIT_STRATEGY: none

  script:
    - dnf install
        --setopt=install_weak_deps=False
        --disablerepo="*modular*"
        -y createrepo_c
    - . artifacts_url.sh
    - mkdir -p repo/{$PRODUCT_NAME,$PRODUCT_NAME-testing}
    - createrepo -v -u $ARTIFACTS_URL -o repo/$PRODUCT_NAME docker-root/target
    - createrepo -v -u $ARTIFACTS_URL -o repo/$PRODUCT_NAME-testing docker-root/target

  artifacts:
    paths:
      - repo/

create-repo:
  extends: .create-repo-base

  # TODO: after GitLab 12.6, use https://docs.gitlab.com/ee/ci/yaml/README.html#artifact-downloads-with-needs
  needs: ['chromium']
  dependencies:
    - chromium

  variables:
    PRODUCT_NAME: chromium

ungoogled-create-repo:
  extends: .create-repo-base

  needs: ['ungoogled-chromium']
  dependencies:
    - 'ungoogled-chromium'

  variables:
    PRODUCT_NAME: ungoogled-chromium

#
# Deploy
#
.repo-deploy-base:
  stage: deploy

  variables:
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME
    UPSTREAM_PROJECT_ID: $CI_PROJECT_ID

  only:
    - tags
    - web

# TODO: after https://gitlab.com/gitlab-org/gitlab/issues/10876 is resolved, use
# `trigger:` in both cases
.repo-deploy-api-base:
  image: fedora:latest
  stage: deploy

  only:
    - tags
    - web

  variables:
    GIT_STRATEGY: none

  script:
    - curl -s --request POST
           --form token=$CI_JOB_TOKEN
           --form ref=master
           --form "variables[UPSTREAM_BRANCH]=$CI_COMMIT_REF_NAME"
           --form "variables[UPSTREAM_PROJECT_ID]=$CI_PROJECT_ID"
           --form "variables[UPSTREAM_JOB_NAME]=$CREATE_REPO_JOB_NAME"
           $CI_API_V4_URL/projects/$DOWNSTREAM_PROJECT_ID/trigger/pipeline

repo-deploy-api:
  extends: .repo-deploy-api-base
  needs: ['create-repo']
  dependencies:
    - create-repo

  variables:
    DOWNSTREAM_PROJECT_ID: 15569783
    CREATE_REPO_JOB_NAME: 'create-repo'

ungoogled-repo-deploy-api:
  extends: .repo-deploy-api-base
  needs: ['ungoogled-create-repo']
  dependencies:
    - 'ungoogled-create-repo'

  variables:
    DOWNSTREAM_PROJECT_ID: 15606466
    CREATE_REPO_JOB_NAME: 'ungoogled-create-repo'

testing-repo-deploy:
  extends: .repo-deploy-base
  needs: ['create-repo']
  variables:
    UPSTREAM_JOB_NAME: 'create-repo'
  trigger:
    project: chromium-ppc64le/dnf/chromium-testing
    strategy: depend

ungoogled-testing-repo-deploy:
  extends: .repo-deploy-base
  needs: ['ungoogled-create-repo']
  variables:
    UPSTREAM_JOB_NAME: 'ungoogled-create-repo'
  trigger:
    project: chromium-ppc64le/dnf/ungoogled-chromium-testing
    strategy: depend

