job:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  only:
    - tags

  tags:
    - ppc64le

  timeout: 6h

  script: make gitlab-build

  artifacts:
    paths:
      - target/*.tar*
      - target/*.rpm

