# Copyright 2019 Colin Samples
#
# SPDX-License-Identifier: Apache-2.0
#

#
# This is the GitLab CI file for building chromium and creating the dnf
# repository
#
# Variables controlling build behavior are listed in README.md. In addition to
# those, defining these variables control the CI behavior:
#
#   NO_REBUILD_CONTAINER  - do not rebuild the build container
#   NO_UNGOOGLED_CHROMIUM - do not build ungoogled chromium
#   NO_STANDARD_CHROMIUM  - do not build standard chromium
#   NO_DEPLOY             - do not deploy the build artifacts to the dnf repo
#   NO_GITHUB_RELEASE     - do not deploy the build artifacts to GitHub
#

stages:
  - prepare
  - build
  - package
  - deploy

variables:
  BUILD_CONTAINER: $CI_REGISTRY_IMAGE/chromium-build-image:$CI_COMMIT_REF_NAME
  GIT_SUBMODULE_STRATEGY: recursive

# Base rule for stages requiring a ppc64le builder
.ppc-build-base:
  image: $BUILD_CONTAINER
  timeout: 16h

  only:
    - tags
    - web

  tags:
    - ppc64le
    - docker

# By default, the CI will build both standard and ungoogled chromium. To only
# build standard chromium, pass the environment variable NO_UNGOOGLED_CHROMIUM
# to the CI job. To only build ungoogled chromium, pass the environment variable
# NO_STANDARD_CHROMIUM
.standard-build-base:
  except:
    variables:
      - $NO_STANDARD_CHROMIUM

.ungoogled-build-base:
  variables:
    UNGOOGLED: 1

  except:
    variables:
      - $NO_UNGOOGLED_CHROMIUM

#
# Prepare Stage
#
build-container:
  extends: .ppc-build-base
  image: fedora:latest
  stage: prepare

  variables:
    _BUILDAH_STARTED_IN_USERNS: ""
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
    GIT_SUBMODULE_STRATEGY: none

  except:
    variables:
      - $NO_REBUILD_CONTAINER

  script:
    - dnf install
        --setopt=install_weak_deps=False
        --disablerepo="*modular*"
        -y buildah
    - sed -e 's/^driver =.*/driver = "vfs"/'
          -e '/^mountopt =.*/d'
          -i /etc/containers/storage.conf
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - buildah bud -t $BUILD_CONTAINER .
    - buildah push $BUILD_CONTAINER

#
# Build Stage
#
.chromium-build-base:
  extends: .ppc-build-base
  stage: build

  script:
    - make -C docker-root -j16
    # TODO: Once https://gitlab.com/gitlab-org/gitlab/issues/22638 is fixed,
    # just pass the variable
    - echo "export ARTIFACTS_URL=$CI_JOB_URL/artifacts/raw/docker-root/target" > artifacts_url.sh

  artifacts:
    paths:
      - docker-root/target/*.tar*
      - docker-root/target/*.rpm
      - docker-root/ccache*xz
      - artifacts_url.sh

  cache:
    key: chromium-build-cache
    paths:
      - docker-root/.ccache
      - docker-root/chromium-*.tar.xz
      - docker-root/llvm-*.tar.zst

chromium:
  extends:
    - .chromium-build-base
    - .standard-build-base

ungoogled:chromium:
  extends:
    - .chromium-build-base
    - .ungoogled-build-base

#
# Package Stage
#
.create-repo-base:
  # This runs on a shared x86 builder
  image: fedora:latest
  stage: package

  only:
    - tags
    - web

  variables:
    GIT_STRATEGY: none

  script:
    - dnf install
        --setopt=install_weak_deps=False
        --disablerepo="*modular*"
        -y createrepo_c
    - . artifacts_url.sh
    - mkdir -p repo/{$PRODUCT_NAME,$PRODUCT_NAME-testing}
    - createrepo -v -u $ARTIFACTS_URL -o repo/$PRODUCT_NAME docker-root/target
    - createrepo -v -u $ARTIFACTS_URL -o repo/$PRODUCT_NAME-testing docker-root/target

  artifacts:
    paths:
      - repo/

create-repo:
  extends:
    - .create-repo-base
    - .standard-build-base

  # TODO: after GitLab 12.6, use https://docs.gitlab.com/ee/ci/yaml/README.html#artifact-downloads-with-needs
  needs: ['chromium']
  dependencies:
    - chromium

  variables:
    PRODUCT_NAME: chromium

ungoogled:create-repo:
  extends:
    - .create-repo-base
    - .ungoogled-build-base

  needs: ['ungoogled:chromium']
  dependencies:
    - 'ungoogled:chromium'

  variables:
    PRODUCT_NAME: ungoogled-chromium

#
# Deploy Stage
#

# Deploy the artifacts to GitHub
.github-deploy-base:
  # This runs on a shared x86 builder
  image: fedora:latest
  stage: deploy

  only:
    - tags
    - web

  allow_failure: true
  when: manual

  except:
    variables:
      - $NO_DEPLOY
      - $NO_GITHUB_RELEASE

  script:
    - dnf install
        --setopt=install_weak_deps=False
        --disablerepo="*modular*"
        -y make perl-Data-Dumper perl-Net-GitHub
    - make github-upload-release artifact_prefix=docker-root

github-deploy:
  extends:
    - .github-deploy-base
    - .standard-build-base

  needs: ['chromium']
  dependencies:
    - chromium

ungoogled:github-deploy:
  extends:
    - .github-deploy-base
    - .ungoogled-build-base

  needs: ['ungoogled:chromium']
  dependencies:
    - 'ungoogled:chromium'

# Deploy the artifacts to the repository
.repo-deploy-base:
  # This runs on a shared x86 builder
  image: fedora:latest
  stage: deploy

  only:
    - tags
    - web

  except:
    variables:
      - $NO_DEPLOY

  variables:
    GIT_STRATEGY: none

  # TODO: after https://gitlab.com/gitlab-org/gitlab/issues/10876 is fixed,
  # consider using `trigger:` syntax
  script:
    - curl -s --request POST
           --form token=$CI_JOB_TOKEN
           --form ref=master
           --form "variables[UPSTREAM_BRANCH]=$CI_COMMIT_REF_NAME"
           --form "variables[UPSTREAM_PROJECT_ID]=$CI_PROJECT_ID"
           --form "variables[UPSTREAM_JOB_ID]=$CI_JOB_ID"
           $CI_API_V4_URL/projects/$DOWNSTREAM_PROJECT_ID/trigger/pipeline

  artifacts:
    paths:
      - repo/

repo-deploy:
  extends:
    - .repo-deploy-base
    - .standard-build-base
  needs: ['create-repo']
  dependencies:
    - create-repo

  variables:
    DOWNSTREAM_PROJECT_ID: 15569783 # chromium-ppc64le/dnf/chromium

ungoogled:repo-deploy:
  extends:
    - .repo-deploy-base
    - .ungoogled-build-base
  needs: ['ungoogled:create-repo']
  dependencies:
    - 'ungoogled:create-repo'

  variables:
    DOWNSTREAM_PROJECT_ID: 15606466 # chromium-ppc64le/dnf/ungoogled-chromium

testing-repo-deploy:
  extends: repo-deploy

  variables:
    DOWNSTREAM_PROJECT_ID: 15569827 # chromium-ppc64le/dnf/chromium-testing

ungoogled:testing-repo-deploy:
  extends: ungoogled:repo-deploy

  variables:
    DOWNSTREAM_PROJECT_ID: 15606460 # chromium-ppc64le/dnf/ungoogled-chromium-testing

