stages:
  - build
  - deploy

build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  only:
    - tags
    - web

  tags:
    - ppc64le

  stage: build

  timeout: 6h

  script:
    - dnf install -y findutils createrepo_c gawk
    - make gitlab-build
    - mkdir -p repo
    - createrepo -v -u ${CI_JOB_URL}/artifacts/raw/target -o repo target

  artifacts:
    paths:
      - target/*.tar*
      - target/*.rpm
      - repo

pages:testing:
  stage: deploy
  dependencies:
    - build

  only:
    - tags
    - web

  tags:
    - ppc64le

  script:
    - cp -R repo public/dnf-repo-testing
    - ./filelist2html.sh public > public/index.html
    - ./filelist2html.sh public/dnf-repo-testing > public/dnf-repo-testing/index.html
    - ./filelist2html.sh public/dnf-repo-testing/repodata > public/dnf-repo-testing/repodata/index.html

  artifacts:
    paths:
      - public


pages:main:
  stage: deploy
  dependencies:
    - build

  only:
    - tags
    - web

  when: manual

  tags:
    - ppc64le

  script:
    - cp -R repo public/dnf-repo
    - cp -R repo public/dnf-repo-testing
    - ./filelist2html.sh public > public/index.html
    - ./filelist2html.sh public/dnf-repo > public/dnf-repo/index.html
    - ./filelist2html.sh public/dnf-repo/repodata > public/dnf-repo/repodata/index.html
    - ./filelist2html.sh public > public/index.html
    - ./filelist2html.sh public/dnf-repo-testing > public/dnf-repo-testing/index.html
    - ./filelist2html.sh public/dnf-repo-testing/repodata > public/dnf-repo-testing/repodata/index.html

  artifacts:
    paths:
      - public

